pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: docker.digital.homeoffice.gov.uk/dq-oag-sftp-docker
    secrets: [ docker_username, docker_password ]
    registry: docker.digital.homeoffice.gov.uk
    context: app
    dockerfile: app/Dockerfile
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
    when:
      event: push
