apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dq-oag-data-ingest
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: dq-oag-data-ingest
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      - name: sftp-key
        secret:
          secretName: dq-oag-data-ingest
          items:
          - key: SSH_PRIVATE_KEY
            path: id_rsa
            mode: 400
      - name: oag-volume
        persistentVolumeClaim:
          claimName: oag-volume
      - name: avdata
        emptyDir: {}
      containers:
      - name: dq-oag-data-ingest
        image: quay.io/ukhomeofficedigital/dq-oag-sftp-docker:{{.DRONE_COMMIT_SHA}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          limits:
            cpu: {{.OAG_CPU_LIMIT}}
            memory: {{.OAG_RAM_LIMIT}}
          requests:
            cpu: {{.OAG_CPU_REQUEST}}
            memory: {{.OAG_RAM_REQUEST}}
        env:
          - name: SSH_REMOTE_HOST_MAYTECH
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: SSH_REMOTE_HOST_MAYTECH
          - name: SSH_REMOTE_USER_MAYTECH
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: SSH_REMOTE_USER_MAYTECH
          - name: SSH_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: SSH_PRIVATE_KEY
          - name: SSH_LANDING_DIR
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: SSH_LANDING_DIR
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: S3_BUCKET_NAME
          - name: S3_KEY_PREFIX
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: S3_KEY_PREFIX
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: S3_ACCESS_KEY_ID
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: S3_SECRET_ACCESS_KEY
          - name: CLAMAV_URL
            value: 127.0.0.1
          - name: CLAMAV_PORT
            value: 3200
        volumeMounts:
        - name: sftp-key
          mountPath: /key
          readOnly: true
        - name: oag-volume
          mountPath: /ADT

      - name: clamav-api
        image: quay.io/ukhomeofficedigital/clamav
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
        - name: UPDATE
          value: "false"
        ports:
        - containerPort: 3200
          name: api
          protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/clamav
            name: avdata
        livenessProbe:
          exec:
            command:
            - /readyness.sh
          initialDelaySeconds: 20
          timeoutSeconds: 2

      - name: clamav
        image: quay.io/ukhomeofficedigital/clamav
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
        - name: UPDATE_ONLY
          value: "true"
        volumeMounts:
        - mountPath: /var/lib/clamav
          name: avdata
        livenessProbe:
          exec:
            command:
            - /readyness.sh
          initialDelaySeconds: 20
          timeoutSeconds: 2
