apiVersion: apps/v1
kind: Deployment
metadata:
  name: dq-oag-data-ingest
  annotations:
    environment: {{ .ENV }}
    {{ if eq .ENV "notprod" }}downscaler/uptime: Mon-Fri 07:00-18:30 Europe/London{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dq-oag-data-ingest
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: dq-oag-data-ingest
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      - name: sftp-key
        secret:
          secretName: dq-oag-data-ingest
          items:
          - key: PRIVATE_KEY
            path: id_rsa
            mode: 400
      - name: oag-volume
        persistentVolumeClaim:
          claimName: oag-volume
      containers:

      - name: dq-oag-data-ingest
        image: quay.io/ukhomeofficedigital/dq-oag-sftp-docker:{{.DRONE_COMMIT_SHA}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          limits:
            cpu: {{.OAG_CPU_LIMIT}}
            memory: {{.OAG_RAM_LIMIT}}
          requests:
            cpu: {{.OAG_CPU_REQUEST}}
            memory: {{.OAG_RAM_REQUEST}}
        env:
          - name: SSH_REMOTE_HOST_MAYTECH
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: SSH_REMOTE_HOST_MAYTECH
          - name: SSH_REMOTE_USER_MAYTECH
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: SSH_REMOTE_USER_MAYTECH
          - name: SSH_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: SSH_PRIVATE_KEY
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: PRIVATE_KEY
          - name: SSH_LANDING_DIR
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: SSH_LANDING_DIR
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: S3_BUCKET_NAME
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: S3_ACCESS_KEY_ID
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: S3_SECRET_ACCESS_KEY
          - name: OAG_RDS_HOST
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: OAG_RDS_HOST
          - name: OAG_RDS_DATABASE
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: OAG_RDS_DATABASE
          - name: OAG_RDS_USERNAME
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: OAG_RDS_USERNAME
          - name: OAG_RDS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: OAG_RDS_PASSWORD
          - name: OAG_RDS_TABLE
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: OAG_RDS_TABLE
          - name: SLACK_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: dq-oag-data-ingest
                key: SLACK_WEBHOOK
          - name: CLAMAV_URL
            value: "dq-clamav"
          - name: CLAMAV_PORT
            value: "443"
        volumeMounts:
        - name: sftp-key
          mountPath: /key
          readOnly: true
        - name: oag-volume
          mountPath: /ADT
