---
apiVersion: v1
kind: Secret
metadata:
  name: dq-oag-data-ingest
type: Opaque
data:
  SSH_REMOTE_HOST_MAYTECH: {{.SSH_REMOTE_HOST_MAYTECH}}
  SSH_REMOTE_USER_MAYTECH: {{.SSH_REMOTE_USER_MAYTECH}}
  SSH_PRIVATE_KEY: {{.SSH_PRIVATE_KEY}}
  PRIVATE_KEY: {{.PRIVATE_KEY}}
  SSH_LANDING_DIR: {{.SSH_LANDING_DIR}}
  S3_BUCKET_NAME: {{.S3_BUCKET_NAME}}
  S3_KEY_PREFIX: {{.S3_KEY_PREFIX}}
  S3_ACCESS_KEY_ID: {{.S3_ACCESS_KEY_ID}}
  S3_SECRET_ACCESS_KEY: {{.S3_SECRET_ACCESS_KEY}}
