---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: dq-oag-data-ingest
  name: dq-oag-data-ingest
spec:
  ports:
  - name: api
    port: 3200
    protocol: TCP
  selector:
    name: dq-oag-data-ingest
